### ISSUE TITLE
Will need to be updated for macOS Big Sur

### ISSUE THREAD

**Issue by shokuninstudio** [iAladdin/NoisyTyper-Swift#6]
The sound effects lag a lot in macOS Big Sur therefore the current build is not recommended.

**Comment by iAladdin** [comment]
I have released v0.2
Please try with Big Sur!
https://github.com/iAladdin/NoisyTyper-Swift/releases/tag/v0.2

**Comment by shokuninstudio** [comment]
Thanks @iAladdin. Please see results below for each SFX:

iPhone - lagging badly, only works if user types very slowly
Classic Typewriter I - perfect
Classic Typewriter II - perfect
1970s Electric Olympia CE 12 - some lagging
1960s Foley Smith Corona - perfect

**Comment by iAladdin** [comment]
@shokuninstudio 

Please try with Version 0.2 Build 328

I have replaced the downloadable file with build 328 binary, please try again!

https://github.com/iAladdin/NoisyTyper-Swift/releases/tag/v0.2

**Comment by shokuninstudio** [comment]
> @shokuninstudio
> 
> Please try with Version 0.2 Build 328
> 
> I have replaced the downloadable file with build 328 binary, please try again!
> 
> https://github.com/iAladdin/NoisyTyper-Swift/releases/tag/v0.2

Same result. Maybe it depends on which Mac model the user has?

**Comment by iAladdin** [comment]
> > @shokuninstudio
> > Please try with Version 0.2 Build 328
> > I have replaced the downloadable file with build 328 binary, please try again!
> > https://github.com/iAladdin/NoisyTyper-Swift/releases/tag/v0.2
> 
> Same result. Maybe it depends on which Mac model the user has?

I don't think so, it should be irrelevant to the model. 
I have tried to run it with my 2013 Macbook Pro, and it works well. 
Please stop old version NoisyTyper and delete it, and then run the new version.
You can check this version info on the dropdown menu now.
Please try with build 329

![image](https://user-images.githubusercontent.com/209606/85945167-79d89680-b96e-11ea-9e09-b86a2c121beb.png)

https://github.com/iAladdin/NoisyTyper-Swift/releases/tag/v0.2

**Comment by shokuninstudio** [comment]
> > > @shokuninstudio
> > > Please try with Version 0.2 Build 328
> > > I have replaced the downloadable file with build 328 binary, please try again!
> > > https://github.com/iAladdin/NoisyTyper-Swift/releases/tag/v0.2
> > 
> > 
> > Same result. Maybe it depends on which Mac model the user has?
> 
> I don't think so, it should be irrelevant to the model.
> I have tried to run it with my 2013 Macbook Pro, and it works well.
> Please stop old version NoisyTyper and delete it, and then run the new version.
> You can check this version info on the dropdown menu now.
> Please try with build 329
>> 
> https://github.com/iAladdin/NoisyTyper-Swift/releases/tag/v0.2

Yes I did that. This is a clean install of Big Sur. No old version of NoisyTyper is installed. I also checked the User/Library folders to see if there were any old preferences to delete.

**Comment by iAladdin** [comment]
Hmmm, no clue at the moment, it could be the audio file that is triggering this issue.
What's your mac model?

Thank you for your feedback and support!

**Comment by shokuninstudio** [comment]
> Hmmm, no clue at the moment, it could be the audio file that is triggering this issue.
> What's your mac model?

MacBook Pro 15" mid-2018

Yes it looks like the audio file is the problem, not the code.

**Comment by iAladdin** [comment]
I convert audio file to 192k mp3, let's try it.
build number is 330

https://github.com/iAladdin/NoisyTyper-Swift/releases/tag/v0.2

@shokuninstudio

**Comment by shokuninstudio** [comment]
> I convert audio file to 192k mp3, let's try it.
> build number is 330
> 
> https://github.com/iAladdin/NoisyTyper-Swift/releases/tag/v0.2
> 
> @shokuninstudio

Thanks. It's a little worse now. The only SFX with the problem are 'iPhone' and '1970s Electric Olympia'. 


<img width="675" alt="Screenshot 2020-06-28 at 14 45 09" src="https://user-images.githubusercontent.com/54727267/85949361-353d0300-b94e-11ea-8a64-8d5debf0f4f5.png">

**Comment by shokuninstudio** [comment]
I see the problem now. When I use 'iPhone' SFX sometimes the sound effect happens **twice** when I press a key. I have to type very slowly to make it work.

**Comment by iAladdin** [comment]
> I see the problem now. When I use 'iPhone' SFX sometimes the sound effect happens **twice** when I press a key. I have to type very slowly to make it work.

<img width="251" alt="image" src="https://user-images.githubusercontent.com/209606/86206863-ef777900-bb9f-11ea-9e31-b67b773c50be.png">


I've refactored the relevant logic and it should work now.

try it ! 

https://github.com/iAladdin/NoisyTyper-Swift/releases/tag/v0.2

**Comment by shokuninstudio** [comment]
> > I see the problem now. When I use 'iPhone' SFX sometimes the sound effect happens **twice** when I press a key. I have to type very slowly to make it work.
> 
> <img alt="image" width="251" src="https://user-images.githubusercontent.com/209606/86206863-ef777900-bb9f-11ea-9e31-b67b773c50be.png">
> 
> I've refactored the relevant logic and it should work now.
> 
> try it !
> 
> https://github.com/iAladdin/NoisyTyper-Swift/releases/tag/v0.2

Still the same problem with the same sound set. It could be an issue with these MacBook Pro 2017-2018 models or this sound set needs to be replaced with completely new audio files.

The problem doesn't exist on older Macs.

**Comment by iAladdin** [comment]
@shokuninstudio 

Sorry about this issue, I think there's nothing I can do for now. Actually, I have replaced those two theme's audio files with new audio encoding format. Maybe I should find some other audio files to replace them.

I have tried with my macs(2013 MBP / 2015 Mac Pro / 2015 MBP / 2019 MBP), indeed I don't have 2017~2018 models, so there maybe have some specific problem with your models, and I can't reproduce it.

Can you make a video for this?

**Comment by shokuninstudio** [comment]
Here's a video

https://wetransfer.com/downloads/d80d0342a942df9b02b82f3defed7c6f20200701094814/8815c08267ba74e27a59946420be696f20200701094829/f32cc7

In the video, twice I typed QWE slowly so there was no lag.

Then twice I typed faster and you can see there is a lag on letter W and then double sound effect on letter E.
